In [1]:
import pandas as pd
import numpy as np


#  How to extend an iterable to the datastructure 

### List

In [2]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1.extend(list2)
list1

[1, 2, 3, 4, 5, 6]

### np.Array

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_combined = np.concatenate([arr1, arr2])
arr_combined

array([1, 2, 3, 4, 5, 6])

### Dictionary

In [4]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict1.update(dict2)
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

### Series

In [5]:
import pandas as pd

s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
s3 = pd.concat([s1, s2], ignore_index=True)
s3

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

### Dataframe

In [6]:
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.concat([df1, df2], ignore_index=True)
df3

A  B
0  1  3
1  2  4
2  5  7
3  6  8

# How to add an item to a data structure

### List

In [7]:
numbers = [1, 2, 3]
# to append the number 4
numbers.append(4)
numbers

[1, 2, 3, 4]

### Array

In [8]:
import numpy as np
arr = np.array([1, 2, 3])
python_list = arr.tolist()
python_list.append(4)
arr = np.array(python_list)
arr

array([1, 2, 3, 4])

### Dictionary- To add a new key,value pair

In [9]:
my_dict={'a':1,'b':2}
my_dict['c']=3
my_dict

{'a': 1, 'b': 2, 'c': 3}

### Dictionary- To add a new value in an existing key

In [10]:
my_dict={'a':1,'b':2}
if not isinstance(my_dict["a"], list):
    my_dict["a"] = [my_dict["a"]]
my_dict["a"].append(3)
my_dict

{'a': [1, 3], 'b': 2}

### Series

In [11]:
import numpy as np
s = pd.Series([1, 2, 3])
python_list = s.tolist()
python_list.append(4)
s = pd.Series(python_list)
s

0    1
1    2
2    3
3    4
dtype: int64

### Dataframe- Adding a new Column

In [12]:
df = pd.DataFrame({
    "names": ["Alice", "Bob"],
    "ages": [25, 30]
})

In [13]:
df["gender"] = ["Female", "Male"]
df

names  ages  gender
0  Alice    25  Female
1    Bob    30    Male

### Dataframe- Adding a new Row

In [14]:
new_row = {"names": "Charlie", "ages": 28, "gender": "Male"}
new_row_df = pd.DataFrame([new_row]) # convert new row into a dataframe
df = pd.concat([df, new_row_df], ignore_index=True) # use concat
df

names  ages  gender
0    Alice    25  Female
1      Bob    30    Male
2  Charlie    28    Male

#  How to insert an item at a position to the datastructure 

### List

In [16]:
lst = [1, 2, 3]
lst.insert(1, 1.5)  # Insert 1.5 at position 1
lst

[1, 1.5, 2, 3]

### np.Array

In [17]:
arr = np.array([1, 2, 3])
arr = np.insert(arr, 1, 1.5)  # Insert 1.5 at position 1
arr

array([1, 1, 2, 3])

### Dictionary - Not Possible

### Series

In [20]:
s_list = s.tolist()
s_list.insert(1, 1.5)
s = pd.Series(s_list)
s

0    1.0
1    1.5
2    2.0
3    3.0
dtype: float64

### Dataframe- Row

In [22]:
# Sample DataFrame
df_sample = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})

# Row to be inserted
new_row = pd.DataFrame({'A': [1.5], 'B': [3.5]})

# Splitting the DataFrame
df_top = df_sample.iloc[:index_to_insert]
df_bottom = df_sample.iloc[index_to_insert:]

# Concatenating the parts with the new row
df_updated = pd.concat([df_top, new_row, df_bottom], ignore_index=True)
df_updated

A    B
0  1.0  3.0
1  1.5  3.5
2  2.0  4.0

### Dataframe: Column

In [23]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df.insert(1, 'A.5', [1.5, 2.5])  # Insert a column named 'A.5' at position 1
df

A  A.5  B
0  1  1.5  3
1  2  2.5  4

#  How to Remove an item from the datastructure 

### List

In [24]:
lst = [1, 2, 3, 2]
lst.remove(2)  # This will remove the first occurrence of 2
lst

[1, 3, 2]

### np.Array

In [25]:
arr = np.array([1, 2, 3, 2])
arr = arr[arr != 2]  # This will remove all occurrences of 2
arr

array([1, 3])

In [27]:
arr = np.array([1, 2, 3, 2])
index_to_remove = np.where(arr == 2)[0][0]  # Find the index of the first occurrence of 2
arr = np.delete(arr, index_to_remove)  # Remove the element at that index
arr

array([1, 3, 2])

### Dictionary - Not Possible

In [28]:
dict_example = {'a': 1, 'b': 2, 'c': 3}
del dict_example['b']  # This will remove the key 'b' and its associated value
dict_example

{'a': 1, 'c': 3}

### Series

In [29]:
s = pd.Series([1, 2, 3, 2])
s = s[s != 2]  # This will remove all occurrences of 2
s

0    1
2    3
dtype: int64

In [31]:
s = pd.Series([1, 2, 3, 2])
# Removing the first occurrence of 2 in the Series
index_to_remove = (s == 2).idxmax()
s_first_removed = s.drop(index_to_remove)

s_first_removed

0    1
2    3
3    2
dtype: int64

### Dataframe- Row

In [32]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df = df[df['A'] != 2]
df

A  B
0  1  4
2  3  6

### Dataframe: Column

In [34]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.drop('A', axis=1, inplace=True)
df

B
0  4
1  5
2  6

#  How to Clear the items from the datastructure 

### List

In [36]:
lst = [1, 2, 3]
lst.clear()
lst

[]

### np.Array

In [38]:
arr = np.array([1, 2, 3])
arr = np.array([])
arr

array([], dtype=float64)

### Dictionary - Not Possible

In [39]:
dict_example = {'a': 1, 'b': 2}
dict_example.clear()
dict_example

{}

### Series

In [41]:
s = pd.Series([1, 2, 3])
s = pd.Series([], dtype='object')
s

Series([], dtype: object)

### Dataframe- Row

In [32]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df = df[df['A'] != 2]
df

A  B
0  1  4
2  3  6

### Dataframe

In [43]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

#  How to Return the index of the first item from the datastructure 

### List

In [45]:
lst = [1, 2, 3, 2]
idx = lst.index(2)  # This will return the index of the first occurrence of 2
idx

1

### np.Array

In [46]:
arr = np.array([1, 2, 3, 2])
idx = np.where(arr == 2)[0][0]
idx

1

### Dictionary

In [48]:
dict_example = {'a': 1, 'b': 2, 'c': 3}
key_for_value = next(key for key, value in dict_example.items() if value == 2)
key_for_value

'b'

### Series

In [49]:
s = pd.Series([1, 2, 3, 2])
idx = (s == 2).idxmax()
idx

1

### Dataframe

In [50]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
idx = (df['A'] == 2).idxmax()
idx

1

#  How to Count the items from the datastructure 

### List

In [51]:
lst = [1, 2, 2, 3]
count = lst.count(2)  # This will return 2 because 2 appears twice
count

2

### np.Array

In [53]:
arr = np.array([1, 2, 2, 3])
count = np.count_nonzero(arr == 2)
count

2

### Dictionary

In [52]:
dict_example = {'a': 1, 'b': 2, 'c': 2}
count = list(dict_example.values()).count(2)
count

2

### Series

In [54]:
s = pd.Series([1, 2, 2, 3])
count = s.value_counts().get(2, 0)
count

2

### Dataframe

In [56]:
#for a specific column
df = pd.DataFrame({'A': [1, 2, 2], 'B': [4, 5, 6]})
count = df['A'].value_counts().get(2, 0)
count

2

In [57]:
# for the entire dataframe
count = (df == 2).sum().sum()
count

2

#  How to Sort the items in the datastructure 

### List

In [58]:
lst = [3, 1, 2]
lst.sort()  # Sorts in ascending order
lst

[1, 2, 3]

### np.Array

In [59]:
arr = np.array([3, 1, 2])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3])

### Dictionary

In [60]:
dict_example = {'b': 2, 'a': 1, 'c': 3}
sorted_keys = sorted(dict_example.keys())
sorted_items = sorted(dict_example.items(), key=lambda x: x[1])  # Sort by value
print('sorted_keys',sorted_keys)
print('sorted_items',sorted_items)

sorted_keys ['a', 'b', 'c']
sorted_items [('a', 1), ('b', 2), ('c', 3)]


### Series

In [61]:
s = pd.Series([3, 1, 2])
sorted_s = s.sort_values()
sorted_s

1    1
2    2
0    3
dtype: int64

### Dataframe

In [62]:
df = pd.DataFrame({'A': [3, 1, 2], 'B': [2, 3, 1]})
sorted_df = df.sort_values(by='A')
sorted_df

A  B
1  1  3
2  2  1
0  3  2

#  How to Reverse the items in the datastructure 

### List

In [63]:
lst = [1, 2, 3]
lst.reverse()
lst

[3, 2, 1]

### np.Array

In [64]:
arr = np.array([1, 2, 3])
reversed_arr = np.flip(arr)
reversed_arr

array([3, 2, 1])

### Dictionary

In [65]:
dict_example = {'a': 1, 'b': 2, 'c': 3}
reversed_dict = dict(reversed(dict_example.items()))
reversed_dict

{'c': 3, 'b': 2, 'a': 1}

### Series

In [66]:
s = pd.Series([1, 2, 3])
reversed_s = s.iloc[::-1]
reversed_s

2    3
1    2
0    1
dtype: int64

### Dataframe

In [67]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
reversed_df = df.iloc[::-1]
reversed_df

A  B
2  3  6
1  2  5
0  1  4

#  How to Convert one to Another Data Structure

### List to Dictionary

In [2]:
lst = [('a', 1), ('b', 2)]
dict_obj = dict(lst)
dict_obj

{'a': 1, 'b': 2}

### Dictionary to List

In [3]:
dict_obj = {'a': 1, 'b': 2}
lst_keys = list(dict_obj.keys())
lst_values = list(dict_obj.values())
lst_keys,lst_values

(['a', 'b'], [1, 2])

### List to np.array

In [4]:
import numpy as np
lst = [1, 2, 3]
arr = np.array(lst)
arr

array([1, 2, 3])

### np.array to List

In [6]:
arr = np.array([1, 2, 3])
lst = arr.tolist()
lst


[1, 2, 3]

### List to Series

In [7]:
import pandas as pd
lst = [1, 2, 3]
series_obj = pd.Series(lst)
series_obj

0    1
1    2
2    3
dtype: int64

### Series to List

In [8]:
series_obj = pd.Series([1, 2, 3])
lst = series_obj.tolist()
lst

[1, 2, 3]

### Dictiionary to Series

In [9]:
dict_obj = {'a': 1, 'b': 2}
series_obj = pd.Series(dict_obj)
series_obj

a    1
b    2
dtype: int64

### Series to Dictionary

In [10]:
series_obj = pd.Series({'a': 1, 'b': 2})
dict_obj = series_obj.to_dict()
dict_obj

{'a': 1, 'b': 2}

### np.array to Series

In [11]:
arr = np.array([1, 2, 3])
series_obj = pd.Series(arr)
series_obj

0    1
1    2
2    3
dtype: int32

### Series to np.array

In [12]:
series_obj = pd.Series([1, 2, 3])
arr = series_obj.values
arr

array([1, 2, 3], dtype=int64)

### Dictonary to Dataframe

In [7]:
dict_obj = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(dict_obj)
df

0    1
1    2
2    3
dtype: int64

###  Dataframe to Dictionary

In [13]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
dict_obj = df.to_dict()
dict_obj

{'col1': {0: 1, 1: 2}, 'col2': {0: 3, 1: 4}}

###  List of Dictionary to dataframe

In [14]:
lst_of_dicts = [{'col1': 1, 'col2': 3}, {'col1': 2, 'col2': 4}]
df = pd.DataFrame(lst_of_dicts)
df

col1  col2
0     1     3
1     2     4

###  Dataframe to List of Dictionaries

In [15]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
lst_of_dicts = df.to_dict('records')
lst_of_dicts

[{'col1': 1, 'col2': 3}, {'col1': 2, 'col2': 4}]

###  np.array to dataframe

In [16]:
arr = np.array([[1, 3], [2, 4]])
df = pd.DataFrame(arr, columns=['col1', 'col2'])
df

col1  col2
0     1     3
1     2     4

###  Dataframe to np.array

In [17]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
arr = df.values
arr

array([[1, 3],
       [2, 4]], dtype=int64)

###  Series to np.array

In [18]:
series_obj = pd.Series([1, 2, 3])
df = series_obj.to_frame()
df

0
0  1
1  2
2  3

###  Series to Dataframe

In [19]:
series_obj = pd.Series([1, 2, 3])
df = series_obj.to_frame()
df

0
0  1
1  2
2  3

###  Dataframe (Single Column) to series

In [20]:
df = pd.DataFrame({'col1': [1, 2, 3]})
series_obj = df['col1']
series_obj

0    1
1    2
2    3
Name: col1, dtype: int64

###  Single List to dataframe

In [21]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
df = pd.DataFrame(lst, columns=['column_name'])
df

column_name
0            1
1            2
2            3
3            4
4            5

###  List of Lists to dataframe

In [22]:
lst_of_lists = [[1, 'A'], [2, 'B'], [3, 'C']]
df = pd.DataFrame(lst_of_lists, columns=['col1', 'col2'])
df

col1 col2
0     1    A
1     2    B
2     3    C

###  Dataframe (Single Column) to list

In [23]:
df = pd.DataFrame({'col1': [1, 2, 3]})
lst = df['col1'].tolist()
lst

[1, 2, 3]

### Entire Dataframe to list of lists

In [24]:
df = pd.DataFrame({'col1': [1, 2], 'col2': ['A', 'B']})
lst_of_lists = df.values.tolist()
lst_of_lists

[[1, 'A'], [2, 'B']]