### Intuition Behind Matrix Factorization

Matrix factorization is a fundamental technique used in recommender systems. It's a bit complex, but I'll try to explain it in an intuitive way:

**Understanding the Matrix**: Imagine you have a large matrix (a grid of numbers) where one dimension represents users and the other represents items (like movies or products). Each cell in this matrix contains the rating a user has given to an item. However, not all cells are filled because not every user has rated every item.

**The Problem of Missing Data**: The main challenge in building a recommender system is that this matrix is mostly empty — most users have only rated a few items. The goal is to predict the missing ratings so we can recommend items that users are likely to enjoy.

**Factorization Concept**: Matrix factorization breaks down this large, mostly empty matrix into two smaller, more manageable matrices. These smaller matrices are usually called 'user factors' and 'item factors'.

**User Factors and Item Factor**s:

**User Factors**: This matrix represents each user with a set of factors or features, which are inferred from their ratings.
**Item Factors**: Similarly, this matrix represents each item with a set of factors.
**Discovering Latent Features**: The factors here are 'latent features'. They might represent hidden characteristics of items (like genre, style, etc. for movies) and user preferences that align with these characteristics. These are not explicitly stated but are inferred from the ratings.

**Multiplying to Predict Ratings**: When we multiply these two smaller matrices, we can approximate the original large matrix. The key idea is that the product of user factors and item factors gives us the predicted ratings for all the items, including those not yet rated by a user.

**Learning the Factors**: The system learns these factors by minimizing the difference between the known ratings and the ratings predicted by the multiplication of the user and item factors. This process usually involves optimization techniques like gradient descent.

**Personalized Recommendation**s: Once the system has learned these factors accurately, it can predict what ratings a user might give to an unwatched movie or unrated product. These predictions are used to recommend items to the user.

In summary, matrix factorization for recommender systems is about breaking down a large, sparse matrix of user-item interactions into smaller, denser matrices that capture the underlying preferences and characteristics. By doing so, the system can predict unknown ratings and make personalized recommendations.

### Demonstration

 Let's create a simple example of matrix factorization for a recommender system in Python. We'll use a small dataset for ease of understanding. Our dataset will be a small user-item rating matrix, and we'll apply matrix factorization to predict missing ratings.

First, we need to set up a basic environment for this task:

We'll create a small matrix of user ratings for different items (movies, for instance).
We'll use NumPy for matrix operations, and a simple matrix factorization method.
In this example, let's assume we have 5 users and 4 items (movies). The users have rated some movies, but not all. Our task is to predict the missing ratings.


The Python code above performed matrix factorization on a simple user-item ratings matrix. Here's a breakdown of what we did:

Created a Ratings Matrix (R): This matrix represented the ratings given by 5 users to 4 items. Ratings ranged from 1 to 5, and a rating of 0 indicated a missing rating.

Initialized User and Item Feature Matrices (U and I): These matrices represent the latent features of users and items. We initialized them with random values.

Set the Parameters: We chose the number of latent features (K), the number of iterations for the optimization process, the learning rate, and the regularization parameter.

Matrix Factorization Process:

We used a method called Stochastic Gradient Descent (SGD) to find the optimal values for U and I.
In each iteration, we updated the values in U and I based on the gradient of the error between the actual rating and the predicted rating.
We only considered the non-zero ratings (i.e., the known ratings) during the update process.
Predicted Ratings: After the matrix factorization, we used the final user and item feature matrices to predict the full ratings matrix. This matrix provides estimates for the missing ratings.

The resulting predicted_ratings matrix shows the estimated ratings for all user-item pairs, including those that were originally missing in the R matrix. These predictions can be used to recommend items to users based on their predicted interests.

This example is a basic demonstration and serves to illustrate the concept. In real-world scenarios, you would use more sophisticated techniques and larger datasets, potentially with additional optimizations and enhancements.

In [1]:
import numpy as np

# Sample ratings matrix (users x items)
# Ratings range from 1 to 5; 0 indicates a missing rating
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 3, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

# Number of factors (latent features)
K = 2

# Initialize user and item latent feature matrices
# Random values are used for the initialization
np.random.seed(0)  # for reproducibility
U = np.random.rand(R.shape[0], K)  # User features matrix
I = np.random.rand(R.shape[1], K)  # Item features matrix

# Parameters for matrix factorization
iterations = 5000  # Number of iterations for the optimization
learning_rate = 0.01  # Learning rate
regularization = 0.02  # Regularization parameter to avoid overfitting

# Function to perform matrix factorization
def matrix_factorization(R, U, I, K, iterations, learning_rate, regularization):
    # Perform Stochastic Gradient Descent
    for iteration in range(iterations):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:  # only consider non-zero ratings
                    # Calculate error
                    eij = R[i][j] - np.dot(U[i, :], I[j, :].T)
                    # Update user and item latent feature matrices
                    U[i, :] += learning_rate * (2 * eij * I[j, :] - regularization * U[i, :])
                    I[j, :] += learning_rate * (2 * eij * U[i, :] - regularization * I[j, :])
    
    return U, I

# Perform matrix factorization
U, I = matrix_factorization(R, U, I, K, iterations, learning_rate, regularization)

# Predict the full ratings matrix
predicted_ratings = np.dot(U, I.T)
predicted_ratings



array([[4.97875256, 2.98180954, 3.45923688, 0.99917092],
       [3.9775769 , 2.39895867, 2.99182212, 1.00468272],
       [1.00407223, 0.98865594, 5.97113337, 4.97199009],
       [0.99809522, 0.90487661, 4.87500487, 3.98297405],
       [1.17979621, 1.01198091, 4.97786318, 3.9982824 ]])

### Vectorized Code ( Same Output)

Vectorizing the code for matrix factorization can make it more efficient, especially for larger datasets. Vectorized operations in Python, typically using NumPy, are generally faster than explicit loops over array elements.

Let's refactor the matrix factorization process using vectorized operations. The core idea remains the same, but we'll replace the explicit loops with matrix operations where possible.

The vectorized version of the matrix factorization code performs the same task as the previous version, but with more efficient operations. Here's a summary of the changes made:

**Vectorized User and Item Updates**: Instead of iterating over each user-item pair individually, the code now processes all the ratings of a single user or a single item in one go. This is done using matrix operations which are inherently faster in NumPy.

**Efficient Error Calculation**: For each user and item, the error between the actual ratings and the predicted ratings is computed in a vectorized manner. This significantly reduces the computational overhead compared to individual error calculations.

**Updated Feature Matrices**:

For each user, the user feature vector is updated based on the error across all items rated by that user.
Similarly, for each item, the item feature vector is updated based on the error across all users who have rated that item.
Final Predicted Ratings: The final predicted ratings are calculated by multiplying the updated user and item feature matrices, just like in the non-vectorized version.

The output predicted_ratings_vectorized shows the estimated ratings for all user-item pairs, including the previously missing ratings. The values might differ slightly from the non-vectorized version due to the nature of floating-point calculations in Python, but the overall concept and results are consistent.

This vectorized approach is more suitable for larger datasets, as it significantly reduces computation time compared to the loop-based approach.

In [2]:
def matrix_factorization_vectorized(R, U, I, K, iterations, learning_rate, regularization):
    users, items = R.shape
    
    for iteration in range(iterations):
        for i in range(users):
            # Indices of items rated by user i
            idx = np.where(R[i, :] > 0)[0]
            I_rated = I[idx, :]
            
            # Error for the items rated by user i
            E_i = R[i, idx] - np.dot(U[i, :], I_rated.T)

            # Update rule for user features
            U[i, :] += learning_rate * (np.dot(E_i, I_rated) - regularization * U[i, :])

        for j in range(items):
            # Indices of users who rated item j
            idx = np.where(R[:, j] > 0)[0]
            U_rated = U[idx, :]
            
            # Error for the users who rated item j
            E_j = R[idx, j] - np.dot(U_rated, I[j, :])

            # Update rule for item features
            I[j, :] += learning_rate * (np.dot(E_j.T, U_rated) - regularization * I[j, :])
    
    return U, I

# Re-initialize user and item latent feature matrices
np.random.seed(0)
U_v = np.random.rand(R.shape[0], K)  # User features matrix
I_v = np.random.rand(R.shape[1], K)  # Item features matrix

# Perform matrix factorization with vectorized operations
U_v, I_v = matrix_factorization_vectorized(R, U_v, I_v, K, iterations, learning_rate, regularization)

# Predict the full ratings matrix with vectorized matrices
predicted_ratings_vectorized = np.dot(U_v, I_v.T)
predicted_ratings_vectorized



array([[4.98861364, 2.98660352, 3.4615647 , 0.99869167],
       [3.98779274, 2.4040358 , 2.99352822, 1.00437938],
       [1.00519089, 0.98708862, 5.95052627, 4.98145458],
       [0.99737953, 0.90217293, 4.85114748, 3.98439629],
       [1.18911693, 1.01614642, 4.97305894, 4.01264932]])

### Code by Splitting the Data

splitting the data into training and test sets is a common practice in machine learning, including in building recommender systems. This allows us to train the model on a subset of the data (training set) and then evaluate its performance on a separate subset (test set) that the model hasn't seen during training. This approach gives a better estimate of how well the model will perform on new, unseen data.

For this example, let's:

Split our existing ratings matrix into a training set and a test set.
Train the matrix factorization model on the training set.
Evaluate the model's performance on the test set.
We'll randomly select a percentage of the known ratings to be part of the test set while ensuring that every user and item has at least one rating in the training set. This step is crucial to avoid cold start issues where a user or item has no ratings in the training set. Let's write the code for this process.

The code has successfully split the original ratings matrix into training and test sets, trained the matrix factorization model on the training data, and made predictions for both sets. Here's an overview:

**Training and Test Sets Creation**:

The create_train_test_sets function converts the ratings matrix into a list of (user, item, rating) tuples.
It then splits this list into training and test sets, ensuring that every user and item is present in the training set.
The training and test sets are converted back into matrix form, with zeros in places where ratings are missing.
Matrix Factorization on Training Data:

We reinitialized the user and item feature matrices (U_train and I_train) and performed matrix factorization on the training set using the vectorized function.
**Predictions**:

Predicted ratings for the training set (predicted_train_ratings) were generated by multiplying the learned user and item feature matrices.
Predictions for the test set (predicted_test_ratings) were obtained similarly, but we only kept the predictions for the entries that are actually part of the test set (i.e., where test_R is non-zero).

**Output Matrices**:

train_R is the training ratings matrix with known ratings used for training and zeros elsewhere.
test_R is the test ratings matrix with known ratings used for testing and zeros elsewhere.
predicted_train_ratings shows the predicted ratings for the training data.
predicted_test_ratings shows the predicted ratings for the test data, with zeros for non-test entries.
This process allows us to evaluate the performance of our matrix factorization model by comparing the predicted ratings against the actual ratings in the test set. In a real-world application, you would use metrics like Root Mean Squared Error (RMSE) to quantify the model's prediction accuracy.

In [3]:
from sklearn.model_selection import train_test_split

def create_train_test_sets(R, test_size=0.2):
    """
    Create training and test sets from the ratings matrix.
    Ensures every user and item has at least one rating in the training set.
    """
    # Convert the ratings matrix to a list of user-item-rating tuples
    ratings_list = [(i, j, R[i, j]) for i in range(R.shape[0]) for j in range(R.shape[1]) if R[i, j] > 0]

    # Train-test split
    train_data, test_data = train_test_split(ratings_list, test_size=test_size, random_state=0)

    # Convert lists back to matrices
    train_matrix = np.zeros(R.shape)
    test_matrix = np.zeros(R.shape)
    for i, j, rating in train_data:
        train_matrix[i, j] = rating
    for i, j, rating in test_data:
        test_matrix[i, j] = rating

    return train_matrix, test_matrix

# Create training and test sets
train_R, test_R = create_train_test_sets(R)

# Re-initialize user and item latent feature matrices for training
U_train = np.random.rand(R.shape[0], K)
I_train = np.random.rand(R.shape[1], K)

# Perform matrix factorization on the training set
U_train, I_train = matrix_factorization_vectorized(train_R, U_train, I_train, K, iterations, learning_rate, regularization)

# Predict ratings on the training set
predicted_train_ratings = np.dot(U_train, I_train.T)

# Predict ratings on the test set
predicted_test_ratings = np.dot(U_train, I_train.T) * (test_R > 0)  # Zero out predictions for non-test entries

# Return the train and test matrices for inspection
train_R, test_R, predicted_train_ratings, predicted_test_ratings



(array([[5., 3., 0., 1.],
        [4., 0., 0., 1.],
        [0., 1., 0., 0.],
        [1., 0., 0., 4.],
        [0., 1., 5., 4.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 3., 0.],
        [1., 0., 0., 5.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[ 4.98968052,  2.98732565,  3.28587718,  0.99813684],
        [ 3.98545094,  2.3387148 ,  2.80315011,  0.99976286],
        [ 1.69155648,  0.99065695,  1.19717718,  0.43275517],
        [ 1.00059267, -0.28508251,  3.99172481,  3.97933104],
        [ 3.00712893,  1.00491708,  4.97879699,  4.00164365]]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  2.80315011,  0.        ],
        [ 1.69155648,  0.        ,  0.        ,  0.43275517],
        [ 0.        , -0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]))

### Using Keras and Embedding Layers

To implement matrix factorization using Keras with embedded layers, we essentially create an embedding for users and an embedding for items (movies, products, etc.). The key idea is to represent users and items in a shared latent space and then to predict ratings by computing the dot product of these embeddings.

Here's a step-by-step guide on how to do this:

**Prepare the Data**: Ensure that user IDs and item IDs are indexed properly (e.g., 0 to N-1 for users and 0 to M-1 for items, where N is the number of users and M is the number of items).

**Create Embeddings**:

**User Embedding**: This layer learns an embedding for each user.
**Item Embedding**: This layer learns an embedding for each item.
**Dot Product**: After obtaining the embeddings, compute the dot product between the user and item embeddings to get the predicted rating.

**Model Definition**: Define a Keras model that takes a user and an item as input and outputs a predicted rating.

**Compile and Train**: Compile the model, specifying an appropriate loss function (like mean squared error for regression) and an optimizer. Then, train the model on the training data.

**Evaluation**: Evaluate the model on test data.

Let's write the code for this. We'll assume that user IDs and item IDs are already appropriately indexed. We'll use the same dataset (matrix R) as before for simplicity, and we'll keep the same train-test split. We need to adjust the data format to be compatible with Keras, and then we can create and train the model.

In [6]:
# Extracting user, item indices, and ratings from the train_R matrix for training the Keras model
train_user_indices = []
train_item_indices = []
train_ratings = []

for user_id in range(train_R.shape[0]):
    for item_id in range(train_R.shape[1]):
        rating = train_R[user_id, item_id]
        if rating > 0:  # If rating is present
            train_user_indices.append(user_id)
            train_item_indices.append(item_id)
            train_ratings.append(rating)

# Convert lists to numpy arrays for Keras
train_user_indices = np.array(train_user_indices)
train_item_indices = np.array(train_item_indices)
train_ratings = np.array(train_ratings)

# Training the model (assuming the model mf_model is already built)
mf_model.fit([train_user_indices, train_item_indices], train_ratings, epochs=100, verbose=1)



Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 10.1839
Epoch 2/100
1/1 [==============================] - 0s 23ms/step - loss: 10.1828
Epoch 3/100
1/1 [==============================] - 0s 24ms/step - loss: 10.1817
Epoch 4/100
1/1 [==============================] - 0s 14ms/step - loss: 10.1806
Epoch 5/100
1/1 [==============================] - 0s 15ms/step - loss: 10.1794
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 10.1783
Epoch 7/100
1/1 [==============================] - 0s 18ms/step - loss: 10.1772
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 10.1760
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 10.1748
Epoch 10/100
1/1 [==============================] - 0s 16ms/step - loss: 10.1737
Epoch 11/100
1/1 [==============================] - 0s 16ms/step - loss: 10.1725
Epoch 12/100
1/1 [==============================] - 0s 18ms/step - loss: 10.1713
Epoch 13/100
1/1 [=====================

In [7]:
from sklearn.metrics import mean_squared_error
from math import sqrt

# Extracting test data
test_user_indices = []
test_item_indices = []
test_actual_ratings = []

for user_id in range(test_R.shape[0]):
    for item_id in range(test_R.shape[1]):
        rating = test_R[user_id, item_id]
        if rating > 0:  # If rating is present
            test_user_indices.append(user_id)
            test_item_indices.append(item_id)
            test_actual_ratings.append(rating)

# Convert lists to numpy arrays for prediction
test_user_indices = np.array(test_user_indices)
test_item_indices = np.array(test_item_indices)
test_actual_ratings = np.array(test_actual_ratings)

# Making predictions
test_predictions = mf_model.predict([test_user_indices, test_item_indices]).flatten()

# Calculate RMSE
rmse = sqrt(mean_squared_error(test_actual_ratings, test_predictions))
print('Test RMSE:', rmse)


1/1 [==============================] - 0s 207ms/step
Test RMSE: 3.36344431403127


### Using Keras with Deep Neural Network

To implement a deep learning-based recommender system using Keras, we can design a neural network that takes user and item embeddings as input and processes them through one or more dense layers. We can also incorporate batch normalization and dropout for regularization and to improve model performance. Here's a step-by-step approach to building such a model:

Create Embeddings for Users and Items: Like before, start with embedding layers for users and items.

Neural Network Layers: After getting the embeddings, we'll pass them through one or more dense (fully connected) layers. We can experiment with the number and size of these layers.

Batch Normalization: Apply batch normalization after each dense layer to normalize the activations and speed up training.

Dropout: Use dropout for regularization to prevent overfitting. Dropout randomly sets a fraction of input units to 0 at each update during training time.

Output Layer: The final layer should output a single value, the predicted rating.

Compile the Model: Choose an appropriate loss function and optimizer.

Train the Model: Fit the model to the training data.

Evaluate the Model: Assess the model's performance on the test set.

Let's write the code for this architecture. Note that the structure and size of the network can be adjusted depending on the specifics of the dataset and the task.

Error analyzing
As before, we're facing the limitation of not having TensorFlow and Keras installed in this environment. However, the provided code snippet outlines the correct approach to building a deep learning-based recommender system using Keras.

Here's a summary of the model architecture and training process:

Model Architecture:

Input Layers: Separate inputs for users and items.
Embedding Layers: Embeddings for users and items.
Flatten and Concatenate: Flatten the embeddings and concatenate them.
Dense Layers: One or more dense layers with ReLU activation. The number of neurons and layers can be tuned.
Batch Normalization: Applied after each dense layer.
Dropout: Applied after each dense layer for regularization.
Output Layer: A single neuron with linear activation to predict the rating.
Model Compilation: The model is compiled with mean squared error as the loss function and the Adam optimizer.

Training: The model is trained on the training data (user indices, item indices, and ratings) for a specified number of epochs and batch size.

Prediction and Evaluation: After training, you can use the model to predict ratings on the test set and evaluate its performance using metrics like RMSE.

To run this code, you need to have TensorFlow and Keras installed in your Python environment. You can install TensorFlow (which includes Keras) using the following command:

In [9]:
import keras
from keras.layers import Dense, Dropout, BatchNormalization

def build_deep_learning_model(num_users, num_items, embedding_size):
    # User and Item input layers
    user_input = Input(shape=(1,), name='user_input')
    item_input = Input(shape=(1,), name='item_input')

    # User and Item embedding layers
    user_embedding = Embedding(output_dim=embedding_size, input_dim=num_users, name='user_embedding')(user_input)
    item_embedding = Embedding(output_dim=embedding_size, input_dim=num_items, name='item_embedding')(item_input)

    # Flatten the embeddings
    user_vector = Flatten()(user_embedding)
    item_vector = Flatten()(item_embedding)

    # Concatenate user and item vectors
    concatenated = keras.layers.Concatenate()([user_vector, item_vector])

    # Neural network layers
    dense = Dense(128, activation='relu')(concatenated)
    dense = BatchNormalization()(dense)
    dense = Dropout(0.5)(dense)

    dense = Dense(64, activation='relu')(dense)
    dense = BatchNormalization()(dense)
    dense = Dropout(0.5)(dense)

    # Output layer
    rating_prediction = Dense(1, activation='linear')(dense)

    # Create and compile the model
    model = Model(inputs=[user_input, item_input], outputs=rating_prediction)
    model.compile(loss='mean_squared_error', optimizer=Adam())

    return model

# Building the deep learning model
dl_model = build_deep_learning_model(num_users, num_items, embedding_size)

# Training the deep learning model
dl_model.fit([train_user_indices, train_item_indices], train_ratings, epochs=100, verbose=1, batch_size=32)



Epoch 1/100
1/1 [==============================] - 3s 3s/step - loss: 17.7713
Epoch 2/100
1/1 [==============================] - 0s 16ms/step - loss: 16.5449
Epoch 3/100
1/1 [==============================] - 0s 16ms/step - loss: 11.9709
Epoch 4/100
1/1 [==============================] - 0s 15ms/step - loss: 7.2800
Epoch 5/100
1/1 [==============================] - 0s 16ms/step - loss: 6.7957
Epoch 6/100
1/1 [==============================] - 0s 16ms/step - loss: 5.2859
Epoch 7/100
1/1 [==============================] - 0s 14ms/step - loss: 11.2176
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 12.3750
Epoch 9/100
1/1 [==============================] - 0s 15ms/step - loss: 10.5441
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 10.9944
Epoch 11/100
1/1 [==============================] - 0s 15ms/step - loss: 11.1406
Epoch 12/100
1/1 [==============================] - 0s 17ms/step - loss: 11.8244
Epoch 13/100
1/1 [========================

In [12]:
from sklearn.metrics import mean_squared_error
from math import sqrt

# Making predictions on the test set
test_predictions = dl_model.predict([test_user_indices, test_item_indices]).flatten()

# Calculate RMSE on the test set
rmse = sqrt(mean_squared_error(test_actual_ratings, test_predictions))
print('Test RMSE:', rmse)


1/1 [==============================] - 0s 38ms/step
Test RMSE: 2.664883849711728


## Implementing with a Residual Network

Implementing matrix factorization with a residual network in a recommender system is an interesting approach. The idea is to combine the concept of matrix factorization, which captures the linear relationships in user-item interactions, with a residual network (ResNet) architecture, which can capture more complex, non-linear interactions. Here's how you can implement this in Keras:

Matrix Factorization Base: Start with the basic matrix factorization model that predicts ratings as the dot product of user and item embeddings.

Residual Blocks: Add one or more residual blocks. Each block should have two or more dense layers with a skip connection that adds the input of the block to its output.

Combine Outputs: Combine the output of the matrix factorization part and the residual blocks. This can be done by adding them or concatenating them, followed by one or more dense layers to produce the final rating prediction.

Compile and Train: Compile the model with an appropriate loss function and optimizer, then train it on your dataset.

Evaluation: Evaluate the model on the test set.

Let's write the code to build this model. The specifics of the model (like the number of residual blocks and the number of neurons in each layer) can be adjusted depending on your dataset and requirements. Since TensorFlow and Keras are not available in this environment, I'll provide a code outline to illustrate the concept:

In [15]:
def build_residual_matrix_factorization_model(num_users, num_items, embedding_size):
    # User and Item input layers
    user_input = Input(shape=(1,), name='user_input')
    item_input = Input(shape=(1,), name='item_input')

    # User and Item embedding layers
    user_embedding = Embedding(output_dim=embedding_size, input_dim=num_users, name='user_embedding')(user_input)
    item_embedding = Embedding(output_dim=embedding_size, input_dim=num_items, name='item_embedding')(item_input)

    # Flatten the embeddings
    user_vector = Flatten()(user_embedding)
    item_vector = Flatten()(item_embedding)

    # Matrix factorization part
    mf_part = Dot(axes=1)([user_vector, item_vector])

    # Residual block
    res_input = Concatenate()([user_vector, item_vector])
    # Ensure the first dense layer in the residual block outputs the same shape as res_input
    res_block = Dense(res_input.shape[1], activation='relu')(res_input)
    res_block = Dense(64, activation='relu')(res_block)
    res_block = Dense(res_input.shape[1], activation='relu')(res_block)  # Match the shape
    res_block = Add()([res_block, res_input])  # Skip connection

    # Combine MF and ResNet parts
    combined = Concatenate()([mf_part, res_block])
    final_output = Dense(1, activation='linear')(combined)

    # Create and compile the model
    model = Model(inputs=[user_input, item_input], outputs=final_output)
    model.compile(loss='mean_squared_error', optimizer='adam')

    return model


In [16]:
# Assuming you have the function `build_residual_matrix_factorization_model` defined as previously discussed

# Number of users and items (for example purposes, replace with actual numbers from your dataset)
num_users = 1000  # Example number, replace with actual number of users in your dataset
num_items = 500   # Example number, replace with actual number of items in your dataset
embedding_size = 20  # Example embedding size, you can adjust this

# Step 1: Build the model
model = build_residual_matrix_factorization_model(num_users, num_items, embedding_size)

# Step 2: Print model summary
model.summary()

# Optional Step 3: Test a training cycle (requires training data)
# model.fit([train_user_indices, train_item_indices], train_ratings, epochs=1, batch_size=32)


Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 user_input (InputLayer)     [(None, 1)]                  0         []                            
                                                                                                  
 item_input (InputLayer)     [(None, 1)]                  0         []                            
                                                                                                  
 user_embedding (Embedding)  (None, 1, 20)                20000     ['user_input[0][0]']          
                                                                                                  
 item_embedding (Embedding)  (None, 1, 20)                10000     ['item_input[0][0]']          
                                                                                            

In [17]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
from math import sqrt

# Assuming you have training data: train_user_indices, train_item_indices, train_ratings
# And test data: test_user_indices, test_item_indices, test_actual_ratings

# Fit the model
model.fit([train_user_indices, train_item_indices], train_ratings, epochs=10, batch_size=32, verbose=1)

# Make predictions on the test set
test_predictions = model.predict([test_user_indices, test_item_indices]).flatten()

# Evaluate the model
# Calculate RMSE
rmse = sqrt(mean_squared_error(test_actual_ratings, test_predictions))
print('Test RMSE:', rmse)

# Calculate MAE
mae = mean_absolute_error(test_actual_ratings, test_predictions)
print('Test MAE:', mae)


Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 10.2154
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 10.1024
Epoch 3/10
1/1 [==============================] - 0s 16ms/step - loss: 9.9875
Epoch 4/10
1/1 [==============================] - 0s 27ms/step - loss: 9.8685
Epoch 5/10
1/1 [==============================] - 0s 18ms/step - loss: 9.7450
Epoch 6/10
1/1 [==============================] - 0s 16ms/step - loss: 9.6175
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 9.4865
Epoch 8/10
1/1 [==============================] - 0s 16ms/step - loss: 9.3558
Epoch 9/10
1/1 [==============================] - 0s 15ms/step - loss: 9.2237
Epoch 10/10
1/1 [==============================] - 0s 168ms/step
Test RMSE: 3.240558979726526
Test MAE: 2.7789201935132346


### Use of Autoencoders

Using autoencoders for a recommender system is an effective approach, especially for handling sparse and high-dimensional data like user-item interaction matrices. Autoencoders can learn to compress the user-item matrix into a lower-dimensional space (encoding) and then reconstruct it (decoding), which helps in capturing the underlying patterns in the data.

Here's a step-by-step guide on how to implement an autoencoder for a recommender system:

Data Preparation:

The input to the autoencoder is typically the user-item interaction matrix.
Normalize or scale the data if necessary.
Autoencoder Architecture:

Encoder: This part of the network compresses the input into a lower-dimensional representation. It typically consists of one or more dense layers, with the dimensionality decreasing in each subsequent layer.
Bottleneck: This layer represents the compressed knowledge of the input data — the encoded representation.
Decoder: The decoder part attempts to reconstruct the input data from the encoded representation. It usually mirrors the encoder in reverse.
Model Training:

The autoencoder is trained by feeding it the user-item matrix and setting the target output to be the same as the input.
The loss function measures how well the autoencoder can reconstruct the input. Mean squared error is a common choice.
Making Predictions:

For recommendations, you can use the output of the decoder. It represents the reconstructed user-item matrix with predictions for the missing items.
Evaluation:

Evaluate the quality of the reconstructed matrix using appropriate metrics, such as RMSE or precision at k.
Here's a basic example in Keras:

In [20]:
import pandas as pd
import numpy as np

# Example data
data = {
    'user_id': [1, 1, 2, 2, 3, 3, 3],
    'item_id': [1, 2, 1, 3, 2, 3, 4],
    'rating': [5, 3, 4, 2, 1, 5, 4]
}

df = pd.DataFrame(data)

# Creating the user-item matrix
user_item_matrix = df.pivot_table(index='user_id', columns='item_id', values='rating')

# Fill missing values with 0 (assuming 0 means no interaction)
user_item_matrix = user_item_matrix.fillna(0)

print(user_item_matrix)


from keras.layers import Input, Dense
from keras.models import Model

def build_autoencoder(input_dim, encoding_dim):
    # Input
    input_layer = Input(shape=(input_dim,))
    
    # Encoder
    encoded = Dense(encoding_dim, activation='relu')(input_layer)
    
    # Decoder
    decoded = Dense(input_dim, activation='sigmoid')(encoded)
    
    # Autoencoder
    autoencoder = Model(input_layer, decoded)
    
    # Encoder model (for later use)
    encoder = Model(input_layer, encoded)

    autoencoder.compile(optimizer='adam', loss='mean_squared_error')
    return autoencoder, encoder

# Assuming you have a user-item matrix 'user_item_matrix'
input_dim = user_item_matrix.shape[1]  # number of items
encoding_dim = 128  # size of the encoding

autoencoder, encoder = build_autoencoder(input_dim, encoding_dim)

# Train the autoencoder
autoencoder.fit(user_item_matrix, user_item_matrix, epochs=50, batch_size=256, shuffle=True)


item_id    1    2    3    4
user_id                    
1        5.0  3.0  0.0  0.0
2        4.0  0.0  2.0  0.0
3        0.0  1.0  5.0  4.0
Epoch 1/50
1/1 [==============================] - 1s 945ms/step - loss: 6.3020
Epoch 2/50
1/1 [==============================] - 0s 11ms/step - loss: 6.2436
Epoch 3/50
1/1 [==============================] - 0s 14ms/step - loss: 6.1856
Epoch 4/50
1/1 [==============================] - 0s 14ms/step - loss: 6.1282
Epoch 5/50
1/1 [==============================] - 0s 16ms/step - loss: 6.0716
Epoch 6/50
1/1 [==============================] - 0s 17ms/step - loss: 6.0161
Epoch 7/50
1/1 [==============================] - 0s 14ms/step - loss: 5.9618
Epoch 8/50
1/1 [==============================] - 0s 15ms/step - loss: 5.9086
Epoch 9/50
1/1 [==============================] - 0s 14ms/step - loss: 5.8568
Epoch 10/50
1/1 [==============================] - 0s 14ms/step - loss: 5.8065
Epoch 11/50
1/1 [==============================] - 0s 18ms/step - loss: 5.7575

In [21]:
from sklearn.metrics import mean_squared_error
from math import sqrt

# Example to create a test set (replace this with your actual test set creation)
# Assuming 'user_item_matrix' is your complete dataset
train_set = user_item_matrix.sample(frac=0.8, random_state=123)  # 80% for training
test_set = user_item_matrix.drop(train_set.index)  # Remaining 20% for testing

# Train the autoencoder (assuming autoencoder is your model)
autoencoder.fit(train_set, train_set, epochs=50, batch_size=256, shuffle=True)

# Predict on the test set
test_predictions = autoencoder.predict(test_set)

# Flatten the test data and predictions to compute RMSE
actual_values = test_set.values.flatten()
predicted_values = test_predictions.flatten()

# Compute RMSE
rmse = sqrt(mean_squared_error(actual_values, predicted_values))
print('Test RMSE:', rmse)


Epoch 1/50
1/1 [==============================] - 0s 13ms/step - loss: 4.1656
Epoch 2/50
1/1 [==============================] - 0s 18ms/step - loss: 4.1582
Epoch 3/50
1/1 [==============================] - 0s 19ms/step - loss: 4.1504
Epoch 4/50
1/1 [==============================] - 0s 17ms/step - loss: 4.1424
Epoch 5/50
1/1 [==============================] - 0s 16ms/step - loss: 4.1343
Epoch 6/50
1/1 [==============================] - 0s 10ms/step - loss: 4.1261
Epoch 7/50
1/1 [==============================] - 0s 18ms/step - loss: 4.1178
Epoch 8/50
1/1 [==============================] - 0s 17ms/step - loss: 4.1095
Epoch 9/50
1/1 [==============================] - 0s 17ms/step - loss: 4.1012
Epoch 10/50
1/1 [==============================] - 0s 18ms/step - loss: 4.0930
Epoch 11/50
1/1 [==============================] - 0s 68ms/step - loss: 4.0849
Epoch 12/50
1/1 [==============================] - 0s 21ms/step - loss: 4.0769
Epoch 13/50
1/1 [==============================] - 0s 22ms/st

In [24]:
import numpy as np
import tensorflow as tf

class RBM:
    def __init__(self, visible_dim, hidden_dim):
        # Initialize parameters with a specific data type (e.g., tf.float32)
        self.W = tf.Variable(tf.random.normal(shape=[visible_dim, hidden_dim], mean=0.0, stddev=0.01, dtype=tf.float32))
        self.bh = tf.Variable(tf.zeros([hidden_dim], dtype=tf.float32))
        self.bv = tf.Variable(tf.zeros([visible_dim], dtype=tf.float32))

    def sample_hidden(self, X):
        # Cast X to the same data type as self.W if necessary
        X = tf.cast(X, dtype=tf.float32)
        h_prob = tf.nn.sigmoid(tf.matmul(X, self.W) + self.bh)
        h_sample = tf.nn.relu(tf.sign(h_prob - tf.random.uniform(tf.shape(h_prob), dtype=tf.float32)))
        return h_sample

    def sample_visible(self, h):
        v_prob = tf.nn.sigmoid(tf.matmul(h, tf.transpose(self.W)) + self.bv)
        v_sample = tf.nn.relu(tf.sign(v_prob - tf.random.uniform(tf.shape(v_prob))))
        return v_sample

    def train(self, X, learning_rate=0.01, batch_size=100, epochs=10):
        for epoch in range(epochs):
            for i in range(0, X.shape[0], batch_size):
                batch_x = X[i:i+batch_size]

                # Contrastive Divergence
                h_sample = self.sample_hidden(batch_x)
                v_sample = self.sample_visible(h_sample)

                positive_grad = tf.matmul(tf.transpose(batch_x), h_sample)
                negative_grad = tf.matmul(tf.transpose(v_sample), h_sample)

                # Update parameters
                self.W.assign_add(learning_rate * (positive_grad - negative_grad) / tf.dtypes.cast(tf.shape(batch_x)[0], tf.float32))
                self.bv.assign_add(learning_rate * tf.reduce_mean(batch_x - v_sample, 0))
                self.bh.assign_add(learning_rate * tf.reduce_mean(h_sample, 0))

            # Monitor training progress
            error = tf.reduce_mean(tf.square(batch_x - v_sample))
            print(f'Epoch: {epoch}, reconstruction error: {error.numpy()}')

    def predict(self, X):
        h = self.sample_hidden(X)
        reconstructed_X = self.sample_visible(h)
        return reconstructed_X

# Assuming you have a user-item interaction matrix 'user_item_matrix'
visible_dim = user_item_matrix.shape[1]  # Number of items
hidden_dim = 64  # Can be tuned

rbm = RBM(visible_dim, hidden_dim)
user_item_matrix = tf.cast(user_item_matrix, dtype=tf.float32)
rbm.train(user_item_matrix, learning_rate=0.01, epochs=10)

# Predict ratings for a user (or a batch of users)
predicted_ratings = rbm.predict(user_item_matrix)
print(predicted_ratings)

Epoch: 0, reconstruction error: 6.0
Epoch: 1, reconstruction error: 6.75
Epoch: 2, reconstruction error: 7.166666507720947
Epoch: 3, reconstruction error: 4.916666507720947
Epoch: 4, reconstruction error: 5.583333492279053
Epoch: 5, reconstruction error: 5.166666507720947
Epoch: 6, reconstruction error: 4.916666507720947
Epoch: 7, reconstruction error: 5.583333492279053
Epoch: 8, reconstruction error: 6.083333492279053
Epoch: 9, reconstruction error: 5.5
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
