In [11]:
from tensorflow.keras.layers import Input,SimpleRNN,Dense,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD,Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
# Make some data
N=1
T=10
D=3
K=2
X=np.random.randn(N,T,D)

In [13]:
# Make an RNN
M=5 # number of hidden units
i= Input(shape=(T,D))
x=SimpleRNN(M)(i)
x=Dense(K)(x)

model=Model(i,x)

In [14]:
# Get the output
Yhat=model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 256ms/step
[[-0.622304   -0.01148811]]


In [15]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense_1 (Dense)             (None, 2)                 12        
                                                                 
Total params: 57 (228.00 Byte)
Trainable params: 57 (228.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.layers[1].get_weights()

[array([[ 0.6499576 ,  0.11976713,  0.3232593 ,  0.18013674,  0.31690186],
        [ 0.6804969 ,  0.8524062 ,  0.09597379, -0.21013719,  0.17415279],
        [-0.05742896,  0.05230957, -0.82196575, -0.27570748,  0.08022481]],
       dtype=float32),
 array([[ 0.03571045,  0.37183568,  0.05109354, -0.9261336 ,  0.01135594],
        [-0.3104643 ,  0.2781922 ,  0.69135225,  0.14487661,  0.57206964],
        [-0.5042895 ,  0.1737008 ,  0.33285612,  0.05915043, -0.7753889 ],
        [-0.00437217, -0.846253  ,  0.4275535 , -0.3166806 , -0.02735131],
        [ 0.8049905 ,  0.1950158 ,  0.47521162,  0.13229477, -0.26576516]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [17]:
# Check their shapes
# should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [18]:
Wx,Wh,bh=model.layers[1].get_weights()
Wo,bo=model.layers[2].get_weights()

In [20]:
h_last=np.zeros(M) # initial hidden state
x=X[0] # the one and only sample
Yhats=[] # where we store the outputs

for t in range(T):
    h=np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
    y=h.dot(Wo)+bo # we only care about this value on the last iteration
    Yhats.append(y)
    
    # important: assign h to h_last
    h_last=h
    
# print the final output
print(Yhats[-1])

[-0.62230406 -0.01148818]
